/**
 * Struktur halaman mengadaptasi pola problem–solution Qontak /solusi/pendidikan.
 * Klaim capability bersumber dari motovax-app (route, sidebar, feature flag,
 * backend service/tool, dan docs/product/modul-fitur-breakdown.md).
 */
(function exposeMotovaxIndustryData() {
  const modules = {
    omnichannel: {
      title: "AI Omnichannel & Call Center",
      desc: "Satukan percakapan WhatsApp, Facebook, dan Instagram; AI, operator, dan PIC bekerja dalam satu alur handoff.",
      href: "../fitur/aplikasi-omnichannel.html",
      code: "OM",
    },
    agentic: {
      title: "Agentic AI",
      desc: "Agen AI 24/7 dengan tool bisnis, konteks tenant, eskalasi manusia, dan pencatatan aksi yang terhubung.",
      href: "../fitur/agentic-ai.html",
      code: "AI",
    },
    crm: {
      title: "Autopilot CRM",
      desc: "Kelola customer, pipeline, assignment, program follow-up, guideline, dan performa tim dari satu workspace.",
      href: "../fitur/aplikasi-crm.html",
      code: "CR",
    },
    social: {
      title: "Social Media & Ads Automation",
      desc: "Buat creative dan caption, jadwalkan posting, kelola campaign, serta hubungkan lead dari kanal Meta.",
      href: "../modul.html#m5-social",
      code: "SM",
    },
    dashboard: {
      title: "One Dashboard & Analytics",
      desc: "Pantau funnel, channel, performa tim, dan metrik lintas lokasi sesuai role dalam satu dashboard.",
      href: "../modul.html#m6-dashboard",
      code: "DB",
    },
    inventory: {
      title: "Inventory Management System",
      desc: "Kelola unit, detail stok, cabang, foto, import data, status, aging, dan insight inventori.",
      href: "../fitur/index.html",
      code: "IM",
    },
    platform: {
      title: "Platform, RBAC & Integrasi",
      desc: "Multi-tenant, users dan roles, konfigurasi, integrasi channel, email report, serta Developer API.",
      href: "../modul.html#m8-platform",
      code: "PL",
    },
    finance: {
      title: "Finance Tools",
      desc: "Simulasi kredit, TNS/GP, analisis finansial internal, trade-in, dan MRP untuk alur dealer.",
      href: "../modul.html",
      code: "FN",
    },
  };

  const industries = {
    pendidikan: {
      slug: "pendidikan",
      name: "Pendidikan",
      status: "adapt",
      statusLabel: "Adaptasi vertical · fondasi Motovax tersedia",
      heroTitle: "Satukan layanan calon siswa, orang tua, dan tim admission",
      heroDesc: "Gunakan fondasi AI omnichannel, CRM, dan dashboard Motovax untuk merespons inquiry, mengatur follow-up pendaftaran, serta menjaga setiap percakapan tetap punya PIC dan status yang jelas.",
      audience: "institusi pendidikan",
      visualTitle: "Admission journey",
      journey: ["Inquiry masuk", "AI jawab FAQ", "Handoff admission", "Follow-up CRM"],
      challenges: [
        { title: "Inquiry tersebar di banyak akun", desc: "Pertanyaan dari WhatsApp, Instagram, dan Facebook sulit dipantau jika tim bekerja dari inbox masing-masing." },
        { title: "Follow-up pendaftaran tidak konsisten", desc: "Minat program, jadwal kunjungan, dan tindak lanjut calon siswa mudah terlewat tanpa pipeline bersama." },
        { title: "Manajemen minim visibilitas", desc: "Tim sulit melihat sumber inquiry, progres admission, dan beban PIC secara cepat." },
      ],
      transformations: [
        { title: "Koordinasi komunikasi", before: "Staf berpindah kanal dan meneruskan screenshot secara manual.", after: "Semua inquiry masuk ke inbox terpadu dengan takeover AI dan handoff ke PIC." },
        { title: "Pipeline admission", before: "Data calon siswa tersebar di chat dan spreadsheet terpisah.", after: "CRM menyimpan customer, minat program, status, assignment, dan jadwal follow-up." },
        { title: "Laporan yang dapat ditindaklanjuti", before: "Rekap kanal dan performa tim dibuat setelah periode selesai.", after: "Dashboard menyajikan funnel dan performa respons dari data operasional yang sama." },
      ],
      moduleRefs: [
        ["omnichannel", "foundation", "Fondasi inbox dan handoff sudah live; nama tim serta routing dikonfigurasi untuk admission."],
        ["crm", "adapt", "Pipeline otomotif perlu dipetakan menjadi inquiry, konsultasi, pendaftaran, dan enrolled."],
        ["agentic", "adapt", "Knowledge dan tool AI perlu diisi program, biaya, jadwal, serta kebijakan institusi."],
        ["dashboard", "adapt", "KPI dikonfigurasi ke inquiry, conversion pendaftaran, dan performa PIC."],
        ["platform", "foundation", "RBAC, multi-tenant, integrasi, dan API tersedia sebagai fondasi."],
      ],
      scopeNote: "Solusi ini berfokus pada customer engagement dan admission. Motovax saat ini bukan SIS, LMS, atau sistem akademik; integrasi ke sistem tersebut dilakukan melalui API sesuai kebutuhan.",
      ctaTitle: "Siap merapikan journey admission Anda?",
      ctaDesc: "Mulai dari channel, pipeline, dan KPI yang paling penting bagi tim penerimaan siswa.",
    },
    keuangan: {
      slug: "keuangan",
      name: "Keuangan",
      status: "adapt",
      statusLabel: "Adaptasi vertical · bukan core banking",
      heroTitle: "Kelola inquiry nasabah dengan respons cepat dan akses terkontrol",
      heroDesc: "Fondasi omnichannel, CRM, role-based access, dan reporting Motovax membantu tim layanan serta sales menangani komunikasi nasabah secara terukur tanpa memisahkan riwayat interaksi.",
      audience: "bisnis jasa keuangan",
      visualTitle: "Customer service journey",
      journey: ["Inquiry nasabah", "AI triage", "Handoff petugas", "Status CRM"],
      challenges: [
        { title: "Riwayat komunikasi terfragmentasi", desc: "Percakapan dari berbagai kanal tidak otomatis membentuk konteks customer yang utuh." },
        { title: "Handoff sensitif sulit diawasi", desc: "Pertanyaan yang perlu petugas manusia harus berpindah tanpa kehilangan konteks atau ownership." },
        { title: "Akses data tidak sesuai peran", desc: "Tim membutuhkan pemisahan akses, tenant, role, dan laporan sesuai tanggung jawab." },
      ],
      transformations: [
        { title: "Layanan omnichannel", before: "Petugas membuka beberapa inbox dan mengulang identifikasi nasabah.", after: "Inbox terpadu mempertahankan riwayat dan mengalihkan kasus ke petugas yang tepat." },
        { title: "Customer pipeline", before: "Status inquiry dan follow-up dicatat dengan format berbeda.", after: "CRM menstandarkan status, assignment, catatan, dan program tindak lanjut." },
        { title: "Governance operasional", before: "Akses dan laporan dibagikan secara luas atau manual.", after: "RBAC, konfigurasi tenant, email report, dan API membentuk kontrol yang lebih jelas." },
      ],
      moduleRefs: [
        ["omnichannel", "foundation", "Inbox WA/FB/IG, takeover, handoff, dan realtime event tersedia sebagai fondasi."],
        ["crm", "adapt", "Entity dan pipeline dikonfigurasi untuk jenis inquiry serta proses layanan keuangan."],
        ["agentic", "adapt", "AI memerlukan knowledge, policy, dan tool yang disetujui untuk konteks keuangan."],
        ["platform", "foundation", "Users, roles, tenant isolation, integrasi, dan Developer API sudah tersedia."],
        ["dashboard", "adapt", "Metrik layanan dan funnel perlu dikonfigurasi sesuai SLA serta proses bisnis."],
      ],
      scopeNote: "Motovax tidak menggantikan core banking, ledger, underwriting, atau sistem transaksi. Halaman ini menjelaskan lapisan customer engagement, CRM, dan integrasi yang dapat diadaptasi.",
      ctaTitle: "Bangun layanan nasabah yang lebih terkoordinasi",
      ctaDesc: "Petakan channel, tipe inquiry, role, dan sistem inti yang perlu diintegrasikan.",
    },
    kesehatan: {
      slug: "kesehatan",
      name: "Kesehatan",
      status: "adapt",
      statusLabel: "Adaptasi vertical · bukan HIS/EMR",
      heroTitle: "Respons inquiry pasien dan handoff layanan dalam satu alur",
      heroDesc: "Gunakan AI omnichannel, CRM follow-up, dan dashboard Motovax untuk merapikan pertanyaan layanan, minat appointment, pengingat komunikasi, serta eskalasi ke petugas manusia.",
      audience: "klinik dan rumah sakit",
      visualTitle: "Patient inquiry journey",
      journey: ["Inquiry pasien", "AI informasi awal", "Handoff petugas", "Follow-up layanan"],
      challenges: [
        { title: "Pertanyaan berulang membebani petugas", desc: "FAQ layanan, lokasi, dan ketersediaan informasi datang bersamaan dari banyak kanal." },
        { title: "Konteks hilang saat eskalasi", desc: "Pasien harus mengulang informasi ketika percakapan berpindah dari AI ke petugas." },
        { title: "Follow-up tidak terukur", desc: "Tim sulit memantau inquiry yang menunggu respons atau perlu tindak lanjut." },
      ],
      transformations: [
        { title: "Front desk digital", before: "Setiap kanal ditangani terpisah dengan respons yang berbeda-beda.", after: "AI menjawab informasi awal dan mengalihkan kasus ke petugas dengan konteks percakapan." },
        { title: "Follow-up terstruktur", before: "Minat appointment dan pertanyaan lanjutan mengandalkan catatan personal.", after: "CRM menyimpan customer, status, assignment, dan jadwal follow-up layanan." },
        { title: "Monitoring layanan", before: "Manajemen melihat performa setelah komplain atau laporan manual.", after: "Dashboard menampilkan funnel inquiry dan performa kanal dari satu data operasional." },
      ],
      moduleRefs: [
        ["omnichannel", "foundation", "Inbox, AI takeover, human handoff, dan monitoring realtime tersedia."],
        ["agentic", "adapt", "Knowledge layanan dan guardrail harus dikonfigurasi; AI tidak memberi diagnosis medis."],
        ["crm", "adapt", "Pipeline disesuaikan menjadi inquiry, appointment interest, follow-up, dan resolved."],
        ["dashboard", "adapt", "KPI layanan pasien dan waktu respons memerlukan konfigurasi vertical."],
        ["platform", "foundation", "Role, tenant, konfigurasi channel, dan API tersedia untuk integrasi."],
      ],
      scopeNote: "Motovax saat ini bukan Hospital Information System, EMR, atau alat diagnosis. Data klinis tetap berada di sistem kesehatan; Motovax dapat menjadi lapisan komunikasi dan follow-up melalui integrasi yang disepakati.",
      ctaTitle: "Rapikan komunikasi layanan pasien",
      ctaDesc: "Mulai dari FAQ, handoff petugas, dan follow-up yang paling sering menimbulkan antrean.",
    },
    "tour-travel": {
      slug: "tour-travel",
      name: "Tour & Travel",
      status: "adapt",
      statusLabel: "Adaptasi vertical · fondasi engagement tersedia",
      heroTitle: "Ubah inquiry perjalanan menjadi follow-up yang terarah",
      heroDesc: "Satukan chat calon pelanggan, automasikan respons awal, kelola minat paket di CRM, dan jalankan konten serta campaign dari fondasi Motovax yang sama.",
      audience: "bisnis tour dan travel",
      visualTitle: "Booking interest journey",
      journey: ["Inquiry paket", "AI kualifikasi", "Handoff travel consultant", "Follow-up CRM"],
      challenges: [
        { title: "Inquiry paket datang serentak", desc: "Pertanyaan destinasi, tanggal, dan budget tersebar di beberapa akun chat." },
        { title: "Penawaran tidak cepat ditindaklanjuti", desc: "Calon pelanggan yang sudah tertarik dapat hilang karena status dan PIC tidak jelas." },
        { title: "Campaign terpisah dari lead", desc: "Konten promosi dan percakapan sales berjalan tanpa funnel bersama." },
      ],
      transformations: [
        { title: "Kualifikasi inquiry", before: "Konsultan mengulang pertanyaan dasar untuk setiap chat masuk.", after: "AI mengumpulkan konteks awal lalu menyerahkan lead ke konsultan dengan riwayat lengkap." },
        { title: "Follow-up paket", before: "Minat destinasi dan tanggal tersimpan di chat personal.", after: "CRM mencatat customer, minat, status, PIC, dan jadwal follow-up." },
        { title: "Konten ke pipeline", before: "Tim membuat promo dan melacak respons secara terpisah.", after: "Social automation dan campaign mendukung alur lead yang dipantau di dashboard." },
      ],
      moduleRefs: [
        ["omnichannel", "foundation", "Inbox dan handoff tersedia untuk menyatukan kanal percakapan."],
        ["crm", "adapt", "Pipeline dikonfigurasi ke inquiry, quotation, booking interest, dan follow-up."],
        ["agentic", "adapt", "Knowledge paket dan tool pencarian perlu diintegrasikan dengan data travel."],
        ["social", "foundation", "Generator, posting terjadwal, dan ads campaign tersedia sebagai fondasi."],
        ["dashboard", "adapt", "Funnel dan metrik perlu dipetakan ke proses travel."],
      ],
      scopeNote: "Motovax belum merupakan reservation engine, GDS, atau ticketing airline. Ketersediaan dan transaksi perjalanan memerlukan integrasi ke sistem booking yang digunakan bisnis.",
      ctaTitle: "Percepat respons calon traveler",
      ctaDesc: "Hubungkan channel, konsultan, paket, dan follow-up dalam journey yang lebih jelas.",
    },
    perhotelan: {
      slug: "perhotelan",
      name: "Perhotelan",
      status: "adapt",
      statusLabel: "Adaptasi vertical · bukan pengganti PMS",
      heroTitle: "Berikan respons tamu yang konsisten sebelum dan sesudah reservasi",
      heroDesc: "Fondasi omnichannel, AI, CRM, dan analytics Motovax membantu mengelola inquiry kamar, minat reservasi, permintaan tamu, serta handoff ke tim hotel.",
      audience: "hotel dan hospitality",
      visualTitle: "Guest journey",
      journey: ["Inquiry tamu", "AI informasi awal", "Handoff reservation", "Follow-up CRM"],
      challenges: [
        { title: "Inquiry masuk dari banyak kanal", desc: "Pertanyaan kamar, fasilitas, dan lokasi ditangani oleh tim berbeda tanpa konteks bersama." },
        { title: "Handoff reservation tidak mulus", desc: "Tamu perlu mengulang kebutuhan saat berpindah dari front desk digital ke petugas." },
        { title: "Riwayat dan performa sulit dibaca", desc: "Manajemen sulit melihat pola inquiry dan kualitas respons lintas shift." },
      ],
      transformations: [
        { title: "Respons tamu 24/7", before: "Pertanyaan dasar menunggu jam operasional petugas.", after: "AI menjawab informasi yang disetujui dan meneruskan kebutuhan kompleks ke manusia." },
        { title: "Handoff dengan konteks", before: "Petugas menerima chat tanpa ringkasan kebutuhan tamu.", after: "Inbox dan CRM menjaga riwayat, status, assignment, dan tindak lanjut." },
        { title: "Visibilitas layanan", before: "Laporan kanal dan petugas disusun secara manual.", after: "Dashboard menyatukan funnel inquiry dan performa tim sesuai role." },
      ],
      moduleRefs: [
        ["omnichannel", "foundation", "Inbox WA/FB/IG, realtime, takeover, dan handoff sudah tersedia."],
        ["agentic", "adapt", "Knowledge hotel dan tool availability memerlukan konfigurasi/integrasi."],
        ["crm", "adapt", "Customer dan pipeline dipetakan ke inquiry serta reservation interest."],
        ["dashboard", "adapt", "KPI guest inquiry dan respons disesuaikan untuk hospitality."],
        ["platform", "foundation", "Role, lokasi/tenant, integrasi, dan API tersedia."],
      ],
      scopeNote: "Motovax bukan PMS, channel manager, atau mesin pembayaran reservasi. Data ketersediaan kamar dan booking final tetap berasal dari sistem hotel melalui integrasi.",
      ctaTitle: "Bangun guest journey yang lebih responsif",
      ctaDesc: "Mulai dari inquiry berulang, handoff reservation, dan laporan layanan lintas shift.",
    },
    logistik: {
      slug: "logistik",
      name: "Logistik",
      status: "adapt",
      statusLabel: "Adaptasi vertical · customer engagement layer",
      heroTitle: "Satukan komunikasi pengirim, penerima, dan tim layanan",
      heroDesc: "Kelola inquiry, keluhan, assignment, dan follow-up pelanggan dari kanal chat ke CRM serta dashboard Motovax tanpa kehilangan ownership.",
      audience: "bisnis logistik",
      visualTitle: "Service case journey",
      journey: ["Inquiry/keluhan", "AI triage", "Handoff operator", "Status & follow-up"],
      challenges: [
        { title: "Volume pertanyaan berulang tinggi", desc: "Pelanggan menanyakan status dan layanan dari berbagai kanal secara bersamaan." },
        { title: "Kasus berpindah tanpa ownership", desc: "Konteks mudah hilang saat keluhan diteruskan ke cabang atau tim operasional." },
        { title: "Laporan layanan terlambat", desc: "Pola keluhan, beban agen, dan status tindak lanjut sulit dipantau real-time." },
      ],
      transformations: [
        { title: "Triage omnichannel", before: "Operator memilah chat secara manual di tiap kanal.", after: "AI mengidentifikasi konteks awal dan mengeskalasi ke manusia dengan riwayat percakapan." },
        { title: "Ownership kasus", before: "Follow-up bergantung pada grup chat dan catatan personal.", after: "CRM menjaga customer, status, PIC, catatan, dan jadwal tindak lanjut." },
        { title: "Monitoring operasional", before: "Rekap kasus dan performa agen baru terlihat belakangan.", after: "Dashboard dan email report memberi visibilitas funnel serta performa layanan." },
      ],
      moduleRefs: [
        ["omnichannel", "foundation", "Inbox, tagging, handoff, pin, close, dan realtime event sudah tersedia."],
        ["crm", "adapt", "Pipeline perlu dipetakan ke inquiry, investigasi, eskalasi, dan resolved."],
        ["agentic", "adapt", "Tool tracking harus diintegrasikan ke TMS atau sumber status pengiriman."],
        ["dashboard", "adapt", "KPI kasus, waktu respons, dan cabang perlu dikonfigurasi."],
        ["platform", "foundation", "Multi-tenant, RBAC, API, dan email report menjadi fondasi integrasi."],
      ],
      scopeNote: "Motovax tidak menggantikan TMS, fleet management, atau sistem tracking. Informasi shipment real-time hanya dapat diberikan setelah integrasi ke sumber operasional logistik.",
      ctaTitle: "Kurangi percakapan layanan yang tercecer",
      ctaDesc: "Petakan kanal, jenis kasus, cabang, dan data tracking yang perlu dihubungkan.",
    },
    fmcg: {
      slug: "fmcg",
      name: "FMCG",
      status: "adapt",
      statusLabel: "Adaptasi vertical · data model perlu disesuaikan",
      heroTitle: "Hubungkan komunikasi distributor, retailer, dan tim sales",
      heroDesc: "Gunakan omnichannel, CRM, social automation, dan dashboard Motovax untuk merapikan inquiry produk, program promosi, assignment sales, dan follow-up channel partner.",
      audience: "bisnis FMCG",
      visualTitle: "Channel sales journey",
      journey: ["Inquiry partner", "AI kualifikasi", "Assign sales", "Follow-up program"],
      challenges: [
        { title: "Komunikasi partner tidak terpusat", desc: "Distributor dan retailer menghubungi banyak nomor serta akun yang berbeda." },
        { title: "Program promosi sulit ditelusuri", desc: "Respons partner dan follow-up sales tidak terhubung dengan campaign yang berjalan." },
        { title: "Visibilitas tim lapangan terbatas", desc: "Manajemen sulit melihat ownership, status, dan performa per area secara konsisten." },
      ],
      transformations: [
        { title: "Partner engagement", before: "Inquiry dan permintaan program tersebar di chat personal.", after: "Inbox terpadu dan CRM menjaga riwayat, status, PIC, serta catatan partner." },
        { title: "Campaign terhubung", before: "Konten promosi dan respons calon partner dilacak terpisah.", after: "Social/ads automation mendukung campaign yang ditindaklanjuti tim sales." },
        { title: "Performa area", before: "Rekap follow-up per area dibuat dari berbagai file.", after: "Dashboard role-based menyatukan funnel dan aktivitas dari data yang sama." },
      ],
      moduleRefs: [
        ["omnichannel", "foundation", "Inbox dan handoff sudah tersedia untuk komunikasi partner."],
        ["crm", "adapt", "Entity customer dan pipeline perlu dipetakan ke distributor/retailer serta program."],
        ["social", "foundation", "Generator, schedule posting, ads campaign, dan Meta publish tersedia."],
        ["dashboard", "adapt", "KPI area, partner, dan program perlu dikonfigurasi."],
        ["inventory", "adapt", "IMS saat ini berbasis unit kendaraan; SKU, batch, dan order FMCG belum menjadi pack live."],
      ],
      scopeNote: "IMS Motovax saat ini khusus unit kendaraan. Pengelolaan SKU, batch, expiry, order, DMS, dan distribusi FMCG memerlukan adaptasi data model atau integrasi ERP.",
      ctaTitle: "Rapikan engagement distributor dan retailer",
      ctaDesc: "Tentukan partner journey, program promosi, area, dan sistem ERP yang menjadi sumber data.",
    },
    ritel: {
      slug: "ritel",
      name: "Ritel",
      status: "adapt",
      statusLabel: "Adaptasi vertical · inventory SKU belum live",
      heroTitle: "Ubah percakapan produk menjadi journey penjualan yang terukur",
      heroDesc: "Satukan chat pelanggan, respons AI, follow-up CRM, konten promosi, dan insight channel menggunakan fondasi Motovax yang dapat dikonfigurasi untuk bisnis ritel.",
      audience: "bisnis ritel",
      visualTitle: "Retail customer journey",
      journey: ["Inquiry produk", "AI respons awal", "Handoff store/sales", "Follow-up CRM"],
      challenges: [
        { title: "Pertanyaan produk tersebar", desc: "Pelanggan bertanya melalui WhatsApp dan media sosial tanpa inbox bersama." },
        { title: "Minat beli tidak menjadi pipeline", desc: "Chat yang potensial sering berhenti tanpa PIC atau jadwal follow-up." },
        { title: "Promo dan hasilnya terpisah", desc: "Tim konten, ads, dan sales melihat data dari tempat yang berbeda." },
      ],
      transformations: [
        { title: "Conversational commerce", before: "Setiap store atau admin menjawab dari akun masing-masing.", after: "Omnichannel dan AI menyatukan respons lalu mengalihkan lead ke tim yang tepat." },
        { title: "Follow-up customer", before: "Minat produk tersimpan sebagai chat tanpa status.", after: "CRM mencatat customer, produk minat, assignment, status, dan follow-up." },
        { title: "Campaign insight", before: "Konten, campaign, dan conversion dibaca secara terpisah.", after: "Social automation dan dashboard membangun alur evaluasi yang lebih terpadu." },
      ],
      moduleRefs: [
        ["omnichannel", "foundation", "WA/FB/IG inbox, AI takeover, dan human handoff tersedia."],
        ["crm", "adapt", "Pipeline perlu disesuaikan untuk inquiry, cart interest, follow-up, dan purchase."],
        ["social", "foundation", "Creative generator, posting, ads campaign, dan Meta publish tersedia."],
        ["dashboard", "adapt", "Funnel produk, store, dan channel memerlukan konfigurasi."],
        ["inventory", "adapt", "IMS kendaraan dapat menjadi referensi, tetapi inventory SKU/POS belum pack live."],
      ],
      scopeNote: "Motovax belum menggantikan POS, commerce checkout, atau inventory SKU. Stok produk dan transaksi perlu diadaptasi atau diintegrasikan dengan sistem ritel yang digunakan.",
      ctaTitle: "Hubungkan chat, promo, dan follow-up ritel",
      ctaDesc: "Mulai dari channel pelanggan, katalog, store, dan funnel penjualan yang paling penting.",
    },
    "teknologi-informasi": {
      slug: "teknologi-informasi",
      name: "Teknologi Informasi",
      status: "adapt",
      statusLabel: "Adaptasi vertical · CRM & engagement foundation",
      heroTitle: "Kelola lead B2B, onboarding, dan komunikasi support dalam satu konteks",
      heroDesc: "Fondasi AI omnichannel, CRM, role-based workspace, dan Developer API Motovax membantu perusahaan teknologi menyatukan journey dari inquiry hingga handoff dan follow-up.",
      audience: "perusahaan teknologi informasi",
      visualTitle: "B2B customer journey",
      journey: ["Inquiry B2B", "AI kualifikasi", "Assign sales/support", "Follow-up CRM"],
      challenges: [
        { title: "Lead dan support bercampur", desc: "Percakapan sales, onboarding, dan bantuan masuk ke kanal yang sama tanpa routing jelas." },
        { title: "Konteks hilang antartim", desc: "Customer harus mengulang kebutuhan saat berpindah dari marketing ke sales atau support." },
        { title: "Funnel dan respons sulit dibandingkan", desc: "Data channel, status customer, dan performa tim berada di sistem berbeda." },
      ],
      transformations: [
        { title: "Routing berdasarkan konteks", before: "Admin memilah lead dan support secara manual.", after: "AI melakukan respons awal dan handoff ke role yang sesuai dengan riwayat lengkap." },
        { title: "B2B pipeline", before: "Opportunity dan onboarding tersebar di chat serta dokumen.", after: "CRM menstandarkan customer, stage, assignment, program, dan guideline." },
        { title: "Integrasi produk", before: "Tim memindahkan data dengan ekspor-impor manual.", after: "Developer API dan konfigurasi tenant menjadi fondasi integrasi sistem eksternal." },
      ],
      moduleRefs: [
        ["omnichannel", "foundation", "Inbox realtime dan handoff AI-manusia sudah tersedia."],
        ["crm", "adapt", "Stage dikonfigurasi untuk lead, discovery, proposal, onboarding, dan customer."],
        ["agentic", "adapt", "Knowledge produk dan action tool harus diintegrasikan sesuai layanan teknologi."],
        ["platform", "foundation", "Developer API, RBAC, multi-tenant, integrasi, dan email report tersedia."],
        ["dashboard", "adapt", "Metrik B2B dan support memerlukan mapping vertical."],
      ],
      scopeNote: "Motovax bukan project management atau IT service management penuh. Ticket lifecycle teknis, engineering issue, dan provisioning produk perlu diintegrasikan dengan tool yang sudah digunakan.",
      ctaTitle: "Satukan customer journey perusahaan teknologi",
      ctaDesc: "Petakan routing lead, support, onboarding, dan integrasi produk Anda.",
    },
    outsourcing: {
      slug: "outsourcing",
      name: "Outsourcing",
      status: "adapt",
      statusLabel: "Adaptasi vertical · multi-tenant foundation",
      heroTitle: "Kelola interaksi multi-klien tanpa kehilangan kontrol operasional",
      heroDesc: "Gunakan inbox omnichannel, AI handoff, workspace per role, multi-tenant, dan analytics Motovax untuk mengatur tim layanan serta konteks klien secara lebih konsisten.",
      audience: "penyedia layanan outsourcing",
      visualTitle: "Multi-client service journey",
      journey: ["Interaksi masuk", "AI triage", "Assign agent/PIC", "Monitor performa"],
      challenges: [
        { title: "Konteks banyak klien mudah tercampur", desc: "Agent menangani brand dan SOP berbeda dari kanal yang beragam." },
        { title: "Handoff dan ownership tidak konsisten", desc: "Kasus berpindah shift atau tim tanpa ringkasan dan status yang jelas." },
        { title: "Laporan performa memakan waktu", desc: "Manajemen harus merekonsiliasi data agent, kanal, dan klien secara manual." },
      ],
      transformations: [
        { title: "Operasi multi-klien", before: "Akun, SOP, dan data klien bercampur dalam tool yang sama.", after: "Tenant, konfigurasi, role, dan channel membantu memisahkan konteks operasional." },
        { title: "Agent handoff", before: "Pergantian agent bergantung pada pesan internal.", after: "Inbox menyimpan riwayat serta mendukung takeover, handoff, escalation, dan close." },
        { title: "Performance visibility", before: "Laporan layanan dikumpulkan setelah shift atau periode selesai.", after: "Dashboard, performa CRM, dan email report memberi data yang lebih cepat ditindaklanjuti." },
      ],
      moduleRefs: [
        ["omnichannel", "foundation", "Fanel AI/agent/MR, realtime, takeover, handoff, dan close sudah tersedia."],
        ["platform", "foundation", "Multi-tenant, RBAC, users, roles, config, dan integration tersedia."],
        ["crm", "adapt", "Status kasus dan struktur klien perlu dipetakan ke CRM Motovax."],
        ["agentic", "adapt", "Knowledge dan SOP agent dikonfigurasi per tenant/klien."],
        ["dashboard", "adapt", "KPI SLA dan produktivitas per klien memerlukan konfigurasi."],
      ],
      scopeNote: "Motovax belum merupakan workforce management, payroll, rostering, atau QA suite BPO penuh. Halaman ini berfokus pada komunikasi, handoff, CRM, dan visibilitas operasional.",
      ctaTitle: "Bangun operasi layanan multi-klien yang lebih rapi",
      ctaDesc: "Mulai dari pemisahan tenant, role agent, routing, dan KPI layanan.",
    },
    otomotif: {
      slug: "otomotif",
      name: "Otomotif",
      status: "live",
      statusLabel: "Vertical utama · modul operasional live",
      heroTitle: "Satukan stok, AI, omnichannel, CRM, dan analytics dealer",
      heroDesc: "Motovax menghubungkan inventory multi-cabang, percakapan pelanggan, follow-up sales, konten, campaign, dan insight dalam platform yang memang dibangun dari operasional dealer.",
      audience: "dealer otomotif",
      visualTitle: "Dealer sales journey",
      journey: ["Lead masuk", "AI cek stok & kredit", "Handoff MR", "Booking & closing"],
      challenges: [
        { title: "Stok dan sales tidak sinkron", desc: "Sales membutuhkan unit ready, detail, foto, cabang, harga, dan status yang selalu konsisten." },
        { title: "Lead hilang di antara channel", desc: "Chat dari WhatsApp dan Meta tidak otomatis menjadi pipeline serta ownership MR." },
        { title: "Manajemen melihat data terlambat", desc: "Revenue, GP, HPP, conversion, dan performa cabang sulit dibaca jika sumbernya terpisah." },
      ],
      transformations: [
        { title: "Inventory sebagai sumber data", before: "Stocklist, foto, dan status tersebar di file serta grup chat.", after: "IMS mengelola unit, cabang, foto, import, aging, dan query stok dari satu sumber." },
        { title: "AI ke closing", before: "Customer menunggu cek stok, simulasi, dan sales yang tersedia.", after: "Jasmine/Falcon memakai tool stok, foto, kredit, follow-up, dan handoff ke MR." },
        { title: "One dashboard", before: "Sales dan management merekap angka dengan definisi berbeda.", after: "Dashboard role-based menyatukan trend sales, revenue, GP, HPP, funnel, dan channel." },
      ],
      moduleRefs: [
        ["inventory", "live", "Daftar/detail/edit unit, cabang, import, foto, stok sales, dan AI inventory live."],
        ["agentic", "live", "Tool stok, media, finance, CRM ops, handoff, konten, trade-in, dan MRP tersedia."],
        ["omnichannel", "live", "WA/FB/IG, realtime SSE, takeover, handoff MR, quick action, dan performa tersedia."],
        ["crm", "live", "Customer, pipeline, program, guideline, MR, salespeople, agents, percakapan, dan dashboard tersedia melalui feature flag."],
        ["social", "live", "Generator creative, posting terjadwal, ads campaign, dan Meta publish tersedia melalui feature flag."],
        ["dashboard", "live", "Sales trend, revenue, GP, HPP, margin, per cabang, sales insight, dan channel metrics tersedia."],
        ["finance", "partial", "Simulasi kredit dan analisis dealer tersedia; belum full accounting ERP."],
      ],
      scopeNote: "Otomotif adalah vertical utama Motovax saat ini. Beberapa modul seperti CRM Autopilot dan Social Media Automation aktif berdasarkan feature flag tenant; finance masih terbatas pada tool dealer, bukan accounting penuh.",
      ctaTitle: "Siap menyatukan operasional dealer Anda?",
      ctaDesc: "Lihat bagaimana stok, AI, channel, sales, dan management bekerja dari satu data.",
    },
    property: {
      slug: "property",
      name: "Property",
      status: "adapt",
      statusLabel: "Adaptasi vertical · scope existing/adapt/new dipisahkan",
      heroTitle: "Hubungkan lead property dari iklan dan chat hingga follow-up sales",
      heroDesc: "Motovax sudah memiliki fondasi omnichannel, AI 24/7, CRM customer, social automation, analytics, dan API; pipeline property, journey per proyek, serta closed-loop akad membutuhkan adaptasi dan pengembangan terarah.",
      audience: "developer dan agen property",
      visualTitle: "Property sales journey",
      journey: ["Lead ads/WA", "AI kualifikasi", "Assign sales/site", "Visit & follow-up"],
      challenges: [
        { title: "Lead tersebar di iklan, form, dan chat", desc: "Ownership serta riwayat calon buyer mudah hilang ketika setiap proyek memakai alur berbeda." },
        { title: "Funnel berhenti sebelum akad", desc: "Site visit, booking, SPK/SPR, KPR, dan akad sering berada di spreadsheet atau sistem terpisah." },
        { title: "Marketing sulit melihat cost per akad", desc: "Data spend dan lead belum otomatis terhubung dengan progres transaksi per proyek." },
      ],
      transformations: [
        { title: "Respons dan routing 24/7", before: "Lead menunggu sales aktif dan percakapan tersimpan di perangkat personal.", after: "Omnichannel serta AI merespons awal, mengumpulkan konteks, dan melakukan handoff ke PIC." },
        { title: "Pipeline property", before: "Status visit hingga akad dicatat dengan format berbeda antarproyek.", after: "CRM Motovax menjadi fondasi; stage property dan entity proyek dikembangkan melalui adaptasi." },
        { title: "Closed-loop analytics", before: "CPL terlihat, tetapi channel yang menghasilkan akad tidak terbaca jelas.", after: "Dashboard existing menjadi fondasi; spend, CAPI, ROAS, dan cost per akad termasuk scope pengembangan." },
      ],
      moduleRefs: [
        ["omnichannel", "foundation", "Call Center WA/FB/IG, AI 24/7, routing, handoff, dan monitoring tersedia."],
        ["crm", "adapt", "Customer 360 dan pipeline tersedia; stage site visit→booking→SPK/SPR→KPR→akad perlu adaptasi."],
        ["social", "foundation", "Creative, posting, ads campaign, Meta publish, dan integrasi channel tersedia."],
        ["dashboard", "adapt", "Dashboard existing perlu KPI project/area, visit, booking, akad, spend, dan ROAS."],
        ["platform", "foundation", "Developer API, tenant, role, configuration, integrations, dan email report tersedia."],
        ["agentic", "adapt", "Knowledge proyek, listing, ketersediaan, dan action booking memerlukan tool vertical property."],
      ],
      scopeNote: "Fondasi customer engagement Motovax sudah ada. Funnel property lengkap, analytics per project, Meta Conversion API hub, buyer profiling, dan entity SPK/SPR/KPR/akad dikategorikan sebagai adaptasi/new build—bukan fitur live yang langsung tersedia.",
      ctaTitle: "Bangun closed-loop journey property Anda",
      ctaDesc: "Mulai dari respon 24/7 dan CRM, lalu petakan project, funnel, CAPI, dan sistem transaksi yang perlu disambungkan.",
    },
  };

  window.MOTOVAX_INDUSTRY_MODULES = modules;
  window.MOTOVAX_INDUSTRIES = industries;
})();
